film_review/urls.py
from django.contrib import admin
from django.urls import include,path
from review import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("review.urls", namespace="reviews"))
]

review/urls.py
from os import name
from django.urls import path
from . import views

app_name = "review"

urlpatterns = [
    path("", views.review_list, name="review_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:slugfied_title>", views.review_detail, name="review_detail"),
    path("<int:review_id>/add_comment", views.add_comment, name="add_comment")
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.utils import timezone


class PublishedManage(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status='10')
     
class Review(models.Model):
    '''Usando 5 e 10 pois caso tenha alguma implementação posterior no codigo como 
    um delete ou review de published temos espaço para colocar outros dados '''
    class status(models.IntegerChoices):
        DRAFT = (5,"Draft")
        PUBLISHED = (10,"Published")

    class RatingChoices(models.IntegerChoices):
        BAD = (0,"0 - BAD")
        POOR = (1,"1 - POOR")
        FAIR = (2,"2 - FAIR")
        GOOD = (3,"3 - GOOD")
        EXCELLENT = (4,"4 - EXCELLENT")
        EXCEPTIONAL = (5,"5 - EXCEPTIONAL")

    title = models.CharField(max_length=200)
    slugfied_title = models.SlugField(max_length=200, unique_for_date="published_ad")
    status = models.IntegerField(choices=status.choices, default=status.DRAFT)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RatingChoices.choices, default=RatingChoices.GOOD)
    id = int 
    
    published_ad = models.DateTimeField(default=timezone.now)
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManage()
    comments: models.Manager["Comment"]

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("reviews:review_detail", 
                       args=[self.published_ad.year, self.published_ad.month,
                                   self.published_ad.day,self.slugfied_title]) 

    def __str__(self) -> str:
        return f"{self.title} - Status: {self.status} - Rating: {self.rating}"
    
class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name="comments")
    user_name = models.CharField(max_length=200)
    user_email = models.EmailField()
    message = models.TextField(max_length=400)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

review/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ["user_name","user_email","message"]

review/views.py
from importlib.metadata import PackageNotFoundError
from django.shortcuts import render, get_object_or_404 
from django.core.paginator import Paginator , PageNotAnInteger, EmptyPage
from .models import Review, Comment
from .forms import CommentForm
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.contrib import messages

def review_list(request): 
    reviews = Review.published.all()
    paginator = Paginator(reviews, 5)
    page_number = request.GET.get("page", 1)

    try:
        review_page = paginator.page(page_number)
    except (PageNotAnInteger,EmptyPage):
        review_page = paginator.page(1)

    return render(request, "review/list.html", {"review_page": review_page})    

def review_detail(request, year, month, day, slugfied_title):
    '''basicamento isso faz retornar um erro 404 e não um error 500 de servidor igual antes'''
    
    form = CommentForm()
    review: Review = get_object_or_404(
        Review.published, 
        published_ad__year=year,
        published_ad__month=month, 
        published_ad__day=day, 
        slugfied_title = slugfied_title
    )
    comments = review.comments.filter(active=True)
    
    return render(request, "review/detail.html", {"review": review, "form": form, "comments": comments})

@require_POST
def add_comment(request, review_id):
    
    review: Review = get_object_or_404(Review.published, id = review_id)
    form = CommentForm( data = request.POST )

    if form.is_valid():
        comment: Comment = form.save(commit=False)
        comment.review = review
        comment.save()
        messages.success(request, "Comment was added successfully!")
        return HttpResponseRedirect(review.get_absolute_url())
    else:
       return render(request, "review/detail.html", {"review": review, "form": form})

review/templates/review/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %} :: Film Reviews</title>
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark justify-content-center">
      <a class="navbar-brand" href="{% url "reviews:review_list" %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-film" viewBox="0 0 16 16">
          <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z"/>
        </svg>
        Film Reviews
      </a>
    </nav>

    <div class="container mt-3">
      <div class="row">

        {% for message in messages %}
          <div class="alert alert-success" role="alert">
            {{ message }}
          </div>
        {% endfor %}

        {% block content %} {% endblock %}
      </div>
    </div>

    <script src="{% static 'bootstrap.bundle.min.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

review/templates/review/detail.html
{% extends 'review/base.html' %}

{% block title %}{{ review.title }}{% endblock %}

{% block content %}

    <div class="col-md-12 mx-auto">
      <div class="card flex-md-row mb-4 h-md-250 border-0">
        <div class="card-body d-flex flex-column align-items-start">
          <h3 class="mb-1">{{ review.title }}</h3>
          <div class="mb-4">
            {{ review.published_ad }}, by <strong>{{ review.author.username }}</strong>
          </div>
          <p class="card-text mb-auto">{{ review.body | linebreaks }}</p>

          <div class="bd-example m-0 border-0 mt-2">
            <h5>
              <span class="badge rounded-pill text-bg-primary">
                {{ review.rating }}
                <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 21 21">
                  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
              </span>
            </h5>

            <a href=""><span class="badge text-bg-secondary">Tag 1</span></a>
            <a href=""><span class="badge text-bg-secondary">Tag 2</span></a>
            <a href=""><span class="badge text-bg-secondary">Tag 3</span></a>
          </div>

          <hr />

          <a href="{% url "reviews:review_list" %}" class="btn btn-light">Voltar</a>

          <hr />
 
          {% with comments_total=comments.count %}
          <h4 class="mb-3">{{ comments_total }} Comment{{ comments_total|pluralize }}: </h4>
          {% endwith %}

          {% for comment in comments %}
            <div class="card mb-4 col-md-6">
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <p>Comment #{{ forloop.counter }}</p>
                  <p>{{ comment.message }}</p>
                  <footer class="blockquote-footer">{{ comment.user_name }} <cite title="Source Title"> - {{ comment.created_at }}</cite></footer>
                </blockquote>
              </div>
            </div>
          {% empty %}
            <h4>There is no comment</h4>
          {% endfor %}



          {% include 'review/includes/comment_form.html' %}
        
        </div>
      </div>    
    </div>
{% endblock %}

review/templates/review/includes/comment_form.html
</div class="card">
    </div class="card-body">
        <h5 class="card-title"> Post your comment </h5>
        <form action="{% url 'review:add_comment' review.id %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Send</button>
        </form>
    </div>
</div>

review/templates/review/list.html
{% extends 'review/base.html' %}

{% block title %}Review List{% endblock %}

{% block content %}

  {% for review in review_page %}
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <h3 class="mb-1">
            <a class="text-dark" href="{{ review.get_absolute_url }}">{{ review.title }}</a>
          </h3>

          <div class="mb-2">
            {{ review.published_ad }},
            by <strong>{{ review.author.username }}</strong>
          </div>

          <p class="card-text mb-auto">{{ review.body | truncatewords:15 }}</p>

          <div class="bd-example m-0 border-0 mt-2">
            <h5>
              <span class="badge rounded-pill text-bg-primary">
                {{ review.rating }}
                <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 21 21">
                  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
              </span>
            </h5>

            <a href=""><span class="badge text-bg-secondary">Tag 1</span></a>
            <a href=""><span class="badge text-bg-secondary">Tag 2</span></a>
            <a href=""><span class="badge text-bg-secondary">Tag 3</span></a>
          </div>

        </div>
      </div>
    </div>
  {% endfor %}
  
  {% include "pagination.html" with page=review_page %}
  
{% endblock %}

templates/pagination.html
<nav aria-label="Navegação de página film review">
    <ul class="pagination">
      <li class="page-item">
        {% if page.has_previous %}
        <a class="page-link" href="?page={{ page.previous_page_number}}" aria-label="Anterior">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        {% endif %}
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
      <li class="page-item"><a class="page-link" href="?page=2">2</a></li>
      <li class="page-item">
        {% if page.has_next %}
        <a class="page-link" href="?page={{ page.next_page_number}}" aria-label="Próximo">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Próximo</span>
        {% endif %}
        </a>
      </li>
    </ul>
  </nav>